/**
 * VANIK — Centralized Mock Data Engine
 * Realistic Indian Merchant Data for Hackathon Demonstration
 * Matches Spring Boot API contracts and Python AI models.
 */

import {
  Merchant,
  KpiMetric,
  RevenueTrendPoint,
  HourlyActivityPoint,
  CategoryBreakdown,
  ProductPerformance,
  CustomerSegment,
  AIInsight,
  GrowthOpportunity,
  Campaign,
  CopilotMessage,
  NotificationItem,
  UpiRecord,
  UpiGrowthMetrics,
  UpiMonthlyTrendPoint,
  UpiMarketSummary,
} from "./types";

export const mockMerchants: Merchant[] = [
  {
    id: "m-001",
    name: "Sharma Tea Corner",
    ownerName: "Ramesh Sharma",
    category: "Food & Beverage",
    location: "Block B, Inner Circle, Connaught Place",
    city: "New Delhi",
    monthlyRevenue: 284500,
    growthRate: -11.4,
    soundboxId: "SB-4G-99218",
    qrCodeId: "QR-CP-8841",
    connectionStatus: "ACTIVE",
    lastSyncedAt: "Realtime Webhook Stream",
  },
  {
    id: "m-002",
    name: "Gupta Kirana & General Store",
    ownerName: "Sunil Gupta",
    category: "Grocery & FMCG",
    location: "Katra Neel, Chandni Chowk",
    city: "Old Delhi",
    monthlyRevenue: 415000,
    growthRate: 4.8,
    soundboxId: "SB-4G-51029",
    qrCodeId: "QR-CC-2219",
    connectionStatus: "ACTIVE",
    lastSyncedAt: "3 mins ago",
  },
  {
    id: "m-003",
    name: "Mehta Electronics",
    ownerName: "Vikram Mehta",
    category: "Electronics",
    location: "Paras Cinema Complex, Nehru Place",
    city: "New Delhi",
    monthlyRevenue: 890000,
    growthRate: -2.1,
    soundboxId: "SB-4G-11048",
    qrCodeId: "QR-NP-7712",
    connectionStatus: "ACTIVE",
    lastSyncedAt: "12 mins ago",
  },
];

export const currentMerchant: Merchant = mockMerchants[0];

export const mockDashboardKpis: KpiMetric[] = [
  {
    id: "kpi-revenue",
    label: "Total Revenue",
    value: "₹2,84,500",
    numericValue: 284500,
    prefix: "₹",
    changePercent: -11.4,
    trend: "down",
    comparisonPeriod: "vs last month",
    subLabel: "₹36,500 below target",
  },
  {
    id: "kpi-transactions",
    label: "Total Transactions",
    value: "1,248",
    numericValue: 1248,
    changePercent: -8.2,
    trend: "down",
    comparisonPeriod: "vs last month",
    subLabel: "112 fewer visits",
  },
  {
    id: "kpi-aov",
    label: "Average Order Value",
    value: "₹228",
    numericValue: 228,
    prefix: "₹",
    changePercent: 3.4,
    trend: "up",
    comparisonPeriod: "vs last month",
    subLabel: "+₹7.50 ticket lift",
  },
  {
    id: "kpi-repeat-customers",
    label: "Repeat Customers",
    value: "312",
    numericValue: 312,
    changePercent: -14.0,
    trend: "down",
    comparisonPeriod: "vs last month",
    subLabel: "312 regulars inactive in 21d",
  },
];

export const mockRevenueTrends7D: RevenueTrendPoint[] = [
  { period: "Mon", currentRevenue: 34200, previousRevenue: 38400, transactions: 152 },
  { period: "Tue", currentRevenue: 36800, previousRevenue: 39100, transactions: 164 },
  { period: "Wed", currentRevenue: 35100, previousRevenue: 38900, transactions: 158 },
  { period: "Thu", currentRevenue: 37900, previousRevenue: 40200, transactions: 169 },
  { period: "Fri", currentRevenue: 44800, previousRevenue: 48200, transactions: 198 },
  { period: "Sat", currentRevenue: 51200, previousRevenue: 57400, transactions: 228 },
  { period: "Sun", currentRevenue: 44500, previousRevenue: 51800, transactions: 179 },
];

export const mockRevenueTrends30D: RevenueTrendPoint[] = [
  { period: "Week 1", currentRevenue: 76400, previousRevenue: 82500, transactions: 335 },
  { period: "Week 2", currentRevenue: 72100, previousRevenue: 81200, transactions: 316 },
  { period: "Week 3", currentRevenue: 68900, previousRevenue: 79800, transactions: 301 },
  { period: "Week 4", currentRevenue: 67100, previousRevenue: 78500, transactions: 296 },
];

export const mockRevenueTrends90D: RevenueTrendPoint[] = [
  { period: "Month -2", currentRevenue: 318000, previousRevenue: 305000, transactions: 1390 },
  { period: "Month -1", currentRevenue: 321000, previousRevenue: 312000, transactions: 1410 },
  { period: "Current", currentRevenue: 284500, previousRevenue: 321000, transactions: 1248 },
];

export const mockRevenueTrends1Y: RevenueTrendPoint[] = [
  { period: "Q1", currentRevenue: 890000, previousRevenue: 820000, transactions: 3920 },
  { period: "Q2", currentRevenue: 940000, previousRevenue: 865000, transactions: 4150 },
  { period: "Q3", currentRevenue: 915000, previousRevenue: 890000, transactions: 4010 },
  { period: "Q4", currentRevenue: 845000, previousRevenue: 920000, transactions: 3720 },
];

export const mockHourlyActivity: HourlyActivityPoint[] = [
  { hour: 7, timeLabel: "7 AM", periodCategory: "Morning", revenue: 12500, transactions: 78, isPeak: false },
  { hour: 8, timeLabel: "8 AM", periodCategory: "Morning", revenue: 24800, transactions: 142, isPeak: true },
  { hour: 9, timeLabel: "9 AM", periodCategory: "Morning", revenue: 28600, transactions: 165, isPeak: true },
  { hour: 10, timeLabel: "10 AM", periodCategory: "Morning", revenue: 19600, transactions: 110, isPeak: false },
  { hour: 11, timeLabel: "11 AM", periodCategory: "Morning", revenue: 14200, transactions: 82, isPeak: false },
  { hour: 12, timeLabel: "12 PM", periodCategory: "Lunch", revenue: 22400, transactions: 118, isPeak: false },
  { hour: 13, timeLabel: "1 PM", periodCategory: "Lunch", revenue: 38900, transactions: 195, isPeak: true },
  { hour: 14, timeLabel: "2 PM", periodCategory: "Lunch", revenue: 36300, transactions: 184, isPeak: true },
  { hour: 15, timeLabel: "3 PM", periodCategory: "Lunch", revenue: 16800, transactions: 92, isPeak: false },
  { hour: 16, timeLabel: "4 PM", periodCategory: "Evening", revenue: 18200, transactions: 98, isPeak: false },
  { hour: 17, timeLabel: "5 PM", periodCategory: "Evening", revenue: 21400, transactions: 104, isPeak: false }, // slumped from 34k
  { hour: 18, timeLabel: "6 PM", periodCategory: "Evening", revenue: 22900, transactions: 112, isPeak: false }, // slumped from 39k
  { hour: 19, timeLabel: "7 PM", periodCategory: "Evening", revenue: 19800, transactions: 96, isPeak: false },  // slumped from 32k
  { hour: 20, timeLabel: "8 PM", periodCategory: "Evening", revenue: 16700, transactions: 82, isPeak: false },
  { hour: 21, timeLabel: "9 PM", periodCategory: "Night", revenue: 10400, transactions: 52, isPeak: false },
  { hour: 22, timeLabel: "10 PM", periodCategory: "Night", revenue: 6800, transactions: 34, isPeak: false },
];

export const mockCategories: CategoryBreakdown[] = [
  { category: "Specialty Tea & Beverages", revenue: 136560, percentage: 48, transactions: 620 },
  { category: "Hot Fresh Snacks", revenue: 91040, percentage: 32, transactions: 412 },
  { category: "Bakery & Breads", revenue: 34140, percentage: 12, transactions: 148 },
  { category: "Packaged Munchies", revenue: 22760, percentage: 8, transactions: 68 },
];

export const mockProducts: ProductPerformance[] = [
  {
    id: "prod-001",
    name: "Special Masala Kulhad Chai",
    category: "Beverages",
    revenue: 105000,
    revenueSharePercent: 36.9,
    unitsSold: 4200,
    averageSellingPrice: 25,
    growthPercent: 12.4,
    trend: "up",
    status: "GROWING",
  },
  {
    id: "prod-002",
    name: "Bun Maska Butter Toast",
    category: "Bakery",
    revenue: 25200,
    revenueSharePercent: 8.8,
    unitsSold: 560,
    averageSellingPrice: 45,
    growthPercent: -31.8,
    trend: "down",
    status: "DECLINING",
  },
  {
    id: "prod-003",
    name: "Paneer Bread Pakora Platter",
    category: "Snacks",
    revenue: 32900,
    revenueSharePercent: 11.5,
    unitsSold: 940,
    averageSellingPrice: 35,
    growthPercent: -24.5,
    trend: "down",
    status: "DECLINING",
  },
  {
    id: "prod-004",
    name: "Ginger Elaichi Chai",
    category: "Beverages",
    revenue: 63000,
    revenueSharePercent: 22.1,
    unitsSold: 2100,
    averageSellingPrice: 30,
    growthPercent: 8.1,
    trend: "up",
    status: "GROWING",
  },
  {
    id: "prod-005",
    name: "Crispy Samosa with Mint Chutney (2 pcs)",
    category: "Snacks",
    revenue: 58400,
    revenueSharePercent: 20.5,
    unitsSold: 2920,
    averageSellingPrice: 20,
    growthPercent: 1.2,
    trend: "up",
    status: "STEADY",
  },
];

export const mockCustomerSegments: CustomerSegment[] = [
  {
    id: "seg-loyal",
    segmentName: "Loyal",
    customerCount: 420,
    percentageOfTotal: 34,
    revenueContribution: 112000,
    averageOrderValue: 266,
    lastPurchaseAvgDays: 2.1,
    churnRiskPercent: 4.2,
    recommendedAction: "Offer early-access seasonal Chai specials",
    description: "High-frequency daily patrons with dependable morning & evening habits.",
  },
  {
    id: "seg-regular",
    segmentName: "Regular",
    customerCount: 680,
    percentageOfTotal: 54,
    revenueContribution: 165000,
    averageOrderValue: 242,
    lastPurchaseAvgDays: 4.6,
    churnRiskPercent: 12.5,
    recommendedAction: "Introduce Paytm Soundbox stamp loyalty card",
    description: "Consistent 2-3 visits weekly, strong response to snack bundles.",
  },
  {
    id: "seg-new",
    segmentName: "New",
    customerCount: 340,
    percentageOfTotal: 27,
    revenueContribution: 68000,
    averageOrderValue: 200,
    lastPurchaseAvgDays: 1.2,
    churnRiskPercent: 28.0,
    recommendedAction: "Send second-visit Paytm coupon (₹20 off on ₹100+)",
    description: "First-time visitors over the last 14 days; onboarding critical.",
  },
  {
    id: "seg-at-risk",
    segmentName: "At Risk",
    customerCount: 147,
    percentageOfTotal: 12,
    revenueContribution: 28500,
    averageOrderValue: 194,
    lastPurchaseAvgDays: 9.4,
    churnRiskPercent: 68.4,
    recommendedAction: "Dispatch automated WhatsApp reactivation reminder",
    description: "Previously regular customers whose visit interval stretched from 3 to 9+ days.",
  },
  {
    id: "seg-inactive",
    segmentName: "Inactive",
    customerCount: 312,
    percentageOfTotal: 25,
    revenueContribution: 0,
    averageOrderValue: 228,
    lastPurchaseAvgDays: 24.8,
    churnRiskPercent: 94.0,
    recommendedAction: "Run high-incentive Win-Back campaign (₹30 cashback on ₹150)",
    description: "Zero visits in past 21 days; represents ₹38k–₹42k recoverable revenue.",
  },
];

export const mockAIInsights: AIInsight[] = [
  {
    id: "ins-001",
    category: "Sales",
    severity: "CRITICAL",
    title: "Evening Footfall Slump Detected",
    observedMetric: "Revenue declined 11.4% overall",
    explanation: "Evening transactions (5:00 PM – 8:30 PM) fell sharply by 31.0%, accounting for 82% of the total monthly revenue shortfall. Meanwhile, morning rush hours remained robust (+4.2%).",
    recommendation: "Deploy a targeted '₹49 Evening Chai & Snack Combo' between 5:00 PM and 8:30 PM.",
    timestamp: "Today at 06:00 AM",
    evidence: [
      "Evening settled receipts dipped by ₹37,200",
      "5–8 PM hourly volume slipped from 105 to 72 orders",
      "Average evening ticket size fell from ₹245 to ₹218",
      "Morning tea peaks (8–10 AM) grew +4.2%",
    ],
    simulatedScenarioAction: "evening offer",
  },
  {
    id: "ins-002",
    category: "Customers",
    severity: "WARNING",
    title: "Sharp Surge in Inactive Regulars",
    observedMetric: "312 regular customers absent for >21 days",
    explanation: "Repeat customer visits contracted by 14.0%. 312 previously loyal patrons have not scanned your Paytm QR in over three weeks, threatening long-term customer lifetime value.",
    recommendation: "Launch an automated WhatsApp/SMS Win-Back campaign with ₹30 cashback on orders above ₹150.",
    timestamp: "Yesterday at 08:30 PM",
    evidence: [
      "Repeat customer rate slipped from 62.0% to 48.2%",
      "Inactive regulars pool expanded by 18% month-over-month",
      "Estimated recoverable revenue pool: ₹38,000 to ₹42,000",
    ],
    simulatedScenarioAction: "win-back campaign",
  },
  {
    id: "ins-003",
    category: "Products",
    severity: "WARNING",
    title: "Bun Maska & Pakora Margin Decoupling",
    observedMetric: "Bun Maska sales down 31.8% (560 units)",
    explanation: "While Masala Chai volume remains high (+12.4%), attach rates for bakery and fried snack items dropped during tea breaks. Customers are buying solo chai without food.",
    recommendation: "Bundle Bun Maska with Kulhad Chai at a combo price of ₹59 (regular ₹70).",
    timestamp: "2 days ago",
    evidence: [
      "Solo beverage orders increased from 38% to 54%",
      "Snack food margin contribution softened by ₹9,400",
      "Chai demand remains inelastic at 4,200 units",
    ],
    simulatedScenarioAction: "bundle offer",
  },
  {
    id: "ins-004",
    category: "Campaigns",
    severity: "OPPORTUNITY",
    title: "Weekend Premium Ticket Opportunity",
    observedMetric: "Weekend AOV is ₹228 (+26.7% vs weekday ₹180)",
    explanation: "Saturday and Sunday visitors consistently purchase higher-value family platters and spend 26.7% more per checkout than weekday single-cup commuters.",
    recommendation: "Launch a 'Family Weekend Chai Platter' targeting Saturday & Sunday afternoons.",
    timestamp: "3 days ago",
    evidence: [
      "Weekend revenue share stands at 38% of weekly total",
      "Snack platter gross margin reaches 52.0%",
      "Average party size on weekends is 2.4 customers",
    ],
    simulatedScenarioAction: "weekend offer",
  },
];

export const mockGrowthOpportunities: GrowthOpportunity[] = [
  {
    id: "opp-001",
    title: "Recover At-Risk & Inactive Customers",
    problem: "18% increase in inactive regulars over the last billing cycle.",
    evidence: "312 customers with 0 visits in 21 days; previously generated ₹41k monthly.",
    recommendedAction: "Launch an automated Paytm Win-Back cashback incentive.",
    estimatedImpact: "+8% to +12% repeat customer lift (₹14,200 revenue)",
    category: "Retention",
    simulatedFixId: "win-back",
    defaultDiscount: 15,
  },
  {
    id: "opp-002",
    title: "Increase Evening Sales Footfall",
    problem: "Evening receipts dropped 31.0% between 5:00 PM and 8:30 PM.",
    evidence: "Average transaction volume fell from 105 to 72 orders during commute hours.",
    recommendedAction: "Promote a ₹49 Happy Hour Chai + Samosa Combo.",
    estimatedImpact: "+₹18,500 estimated monthly incremental revenue",
    category: "Sales",
    simulatedFixId: "evening-offer",
    defaultDiscount: 10,
  },
  {
    id: "opp-003",
    title: "Improve Chai Attach & Repeat Purchases",
    problem: "54% of customers buy solo tea without snack attachments.",
    evidence: "Bun Maska units slumped -31.8% and Bread Pakoras fell -24.5%.",
    recommendedAction: "Create default ₹59 Chai & Butter Bun pairing at checkout.",
    estimatedImpact: "+14.2% lift in average order value (AOV)",
    category: "Product",
    simulatedFixId: "bundle-offer",
    defaultDiscount: 12,
  },
  {
    id: "opp-004",
    title: "Capitalize on High-Ticket Weekends",
    problem: "Weekend ticket size is ₹228 but promotional coverage is zero.",
    evidence: "Weekends account for 38% revenue with 52% margin on family platters.",
    recommendedAction: "Run targeted Weekend Chai & Pakora Platter campaigns.",
    estimatedImpact: "+₹10,200 simulated revenue gain over 7 days",
    category: "Sales",
    simulatedFixId: "weekend-offer",
    defaultDiscount: 15,
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: "camp-001",
    name: "Evening Happy Hour Flash Offer",
    type: "Flash Offer",
    targetSegment: "Commuters & Regulars (5–8 PM)",
    duration: "14 Days",
    durationDays: 14,
    discountPercent: 10,
    budget: 500,
    revenueImpact: 18500,
    roi: 4.8,
    status: "Active",
    reach: 650,
    conversions: 240,
    startDate: "2026-09-04",
  },
  {
    id: "camp-002",
    name: "Weekend Family Platter Special",
    type: "Weekend Special",
    targetSegment: "Weekend Visitors",
    duration: "4 Weekends",
    durationDays: 8,
    discountPercent: 15,
    budget: 1200,
    revenueImpact: 14600,
    roi: 2.1,
    status: "Completed",
    reach: 820,
    conversions: 185,
    startDate: "2026-08-15",
  },
  {
    id: "camp-003",
    name: "Paytm Win-Back Stamp Voucher",
    type: "Win-back Coupon",
    targetSegment: "312 Inactive Regulars",
    duration: "21 Days",
    durationDays: 21,
    discountPercent: 20,
    budget: 800,
    revenueImpact: 0,
    roi: 0,
    status: "Draft",
    reach: 312,
    conversions: 0,
    startDate: "2026-09-20",
  },
];

export const initialCopilotMessages: CopilotMessage[] = [
  {
    id: "copilot-welcome",
    sender: "ai",
    timestamp: "12:00 PM",
    content: "Good afternoon, Ramesh Ji! I am **VANIK Growth Copilot**, your real-time AI business advisor.\n\nI have analyzed your last 30 days of transaction receipts and detected actionable opportunities in your evening footfall and customer retention.",
    dataSection: {
      metric: "Monthly Revenue",
      value: "₹2,84,500 (↓ 11.4%)",
      trend: "down",
      details: "Primarily driven by a 31% dip in 5:00 PM – 8:30 PM transactions",
    },
    insightSection: "Your core daytime chai sales are strong (+4.2%), but 312 regular customers stopped visiting in the evening.",
    recommendationSection: "Try running a ₹49 Evening Combo or simulate a 10% discount to test expected customer response.",
    citedMetrics: [
      "Revenue: ₹2,84,500 (-11.4%)",
      "Evening slump: -31.0%",
      "Inactive Regulars: 312",
    ],
    quickActions: [
      { label: "Why are my sales down?", action: "ask", target: "Why are my sales down?" },
      { label: "What happens if I give 10% discount?", action: "ask", target: "What happens if I give 10% discount?" },
      { label: "Which customers should I target?", action: "ask", target: "Which customers should I target?" },
    ],
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: "notif-1",
    title: "Critical Slump Detected",
    description: "Evening transaction volume fell 31% over past 14 days.",
    type: "ALERT",
    timestamp: "10m ago",
    read: false,
    link: "/insights",
  },
  {
    id: "notif-2",
    title: "AI Simulation Ready",
    description: "What-If Simulator calculated +₹9,200 lift for 10% Evening Promo.",
    type: "INSIGHT",
    timestamp: "1h ago",
    read: false,
    link: "/simulator",
  },
  {
    id: "notif-3",
    title: "Campaign Outcome Recorded",
    description: "Evening Happy Hour achieved 4.8x ROI (+240 txns).",
    type: "CAMPAIGN",
    timestamp: "Yesterday",
    read: true,
    link: "/campaigns",
  },
];

// ============================================================================
// Official NPCI UPI Macroeconomic Statistics (Source: NPCI)
// Strictly isolated from merchant/customer synthetic datasets.
// ============================================================================

export const mockUpiMonthlyTrends: UpiMonthlyTrendPoint[] = [
  {
    month: "August 2025",
    yearMonth: "2025-08",
    transactionVolumeMillion: 20008.31,
    transactionVolumeBillion: 20.01,
    avgDailyTransactionVolumeMillion: 645.4294,
    transactionValueCrore: 2485472.9,
    transactionValueLakhCrore: 24.85,
    avgDailyTransactionValueCrore: 80176.5452,
    banksLiveOnUpi: 688,
    source: "NPCI",
  },
  {
    month: "September 2025",
    yearMonth: "2025-09",
    transactionVolumeMillion: 19633.43,
    transactionVolumeBillion: 19.63,
    avgDailyTransactionVolumeMillion: 654.4478,
    transactionValueCrore: 2489736.52,
    transactionValueLakhCrore: 24.9,
    avgDailyTransactionValueCrore: 82991.2173,
    banksLiveOnUpi: 686,
    source: "NPCI",
  },
  {
    month: "October 2025",
    yearMonth: "2025-10",
    transactionVolumeMillion: 20700.92,
    transactionVolumeBillion: 20.7,
    avgDailyTransactionVolumeMillion: 667.7716,
    transactionValueCrore: 2727790.71,
    transactionValueLakhCrore: 27.28,
    avgDailyTransactionValueCrore: 87993.2487,
    banksLiveOnUpi: 683,
    source: "NPCI",
  },
  {
    month: "November 2025",
    yearMonth: "2025-11",
    transactionVolumeMillion: 20466.98,
    transactionVolumeBillion: 20.47,
    avgDailyTransactionVolumeMillion: 682.2326,
    transactionValueCrore: 2631632.64,
    transactionValueLakhCrore: 26.32,
    avgDailyTransactionValueCrore: 87721.088,
    banksLiveOnUpi: 684,
    source: "NPCI",
  },
  {
    month: "December 2025",
    yearMonth: "2025-12",
    transactionVolumeMillion: 21634.67,
    transactionVolumeBillion: 21.63,
    avgDailyTransactionVolumeMillion: 697.8925,
    transactionValueCrore: 2796712.71,
    transactionValueLakhCrore: 27.97,
    avgDailyTransactionValueCrore: 90216.539,
    banksLiveOnUpi: 685,
    source: "NPCI",
  },
  {
    month: "January 2026",
    yearMonth: "2026-01",
    transactionVolumeMillion: 21703.46,
    transactionVolumeBillion: 21.7,
    avgDailyTransactionVolumeMillion: 700.1116,
    transactionValueCrore: 2833481.26,
    transactionValueLakhCrore: 28.33,
    avgDailyTransactionValueCrore: 91402.6213,
    banksLiveOnUpi: 691,
    source: "NPCI",
  },
  {
    month: "February 2026",
    yearMonth: "2026-02",
    transactionVolumeMillion: 20394.2,
    transactionVolumeBillion: 20.39,
    avgDailyTransactionVolumeMillion: 728.3643,
    transactionValueCrore: 2684229.3,
    transactionValueLakhCrore: 26.84,
    avgDailyTransactionValueCrore: 95865.3321,
    banksLiveOnUpi: 694,
    source: "NPCI",
  },
  {
    month: "March 2026",
    yearMonth: "2026-03",
    transactionVolumeMillion: 22641.14,
    transactionVolumeBillion: 22.64,
    avgDailyTransactionVolumeMillion: 730.3594,
    transactionValueCrore: 2952542.03,
    transactionValueLakhCrore: 29.53,
    avgDailyTransactionValueCrore: 95243.2913,
    banksLiveOnUpi: 705,
    source: "NPCI",
  },
  {
    month: "April 2026",
    yearMonth: "2026-04",
    transactionVolumeMillion: 22346.8,
    transactionVolumeBillion: 22.35,
    avgDailyTransactionVolumeMillion: 744.8932,
    transactionValueCrore: 2902988.05,
    transactionValueLakhCrore: 29.03,
    avgDailyTransactionValueCrore: 96766.2683,
    banksLiveOnUpi: null,
    source: "NPCI",
  },
  {
    month: "May 2026",
    yearMonth: "2026-05",
    transactionVolumeMillion: 23201.95,
    transactionVolumeBillion: 23.2,
    avgDailyTransactionVolumeMillion: 748.45,
    transactionValueCrore: 2990424.18,
    transactionValueLakhCrore: 29.9,
    avgDailyTransactionValueCrore: 96465.2961,
    banksLiveOnUpi: null,
    source: "NPCI",
  },
  {
    month: "June 2026",
    yearMonth: "2026-06",
    transactionVolumeMillion: 22716.08,
    transactionVolumeBillion: 22.72,
    avgDailyTransactionVolumeMillion: 757.2027,
    transactionValueCrore: 2892138.66,
    transactionValueLakhCrore: 28.92,
    avgDailyTransactionValueCrore: 96404.622,
    banksLiveOnUpi: null,
    source: "NPCI",
  },
  {
    month: "July 2026",
    yearMonth: "2026-07",
    transactionVolumeMillion: 23658.35,
    transactionVolumeBillion: 23.66,
    avgDailyTransactionVolumeMillion: 763.1726,
    transactionValueCrore: 2987880.48,
    transactionValueLakhCrore: 29.88,
    avgDailyTransactionValueCrore: 96383.2413,
    banksLiveOnUpi: null,
    source: "NPCI",
  },
  {
    month: "August 2026",
    yearMonth: "2026-08",
    transactionVolumeMillion: 24508.95,
    transactionVolumeBillion: 24.51,
    avgDailyTransactionVolumeMillion: 790.6113,
    transactionValueCrore: 2982355.93,
    transactionValueLakhCrore: 29.82,
    avgDailyTransactionValueCrore: 96205.03,
    banksLiveOnUpi: null,
    source: "NPCI",
  },
  {
    month: "September 2026",
    yearMonth: "2026-09",
    transactionVolumeMillion: 14007.57,
    transactionVolumeBillion: 14.01,
    avgDailyTransactionVolumeMillion: 823.9747,
    transactionValueCrore: 1777116.52,
    transactionValueLakhCrore: 17.77,
    avgDailyTransactionValueCrore: 104536.2659,
    banksLiveOnUpi: null,
    source: "NPCI",
  },
];

export const mockUpiLatest: UpiRecord = {
  month: "August 2026",
  yearMonth: "2026-08",
  transactionVolumeMillion: 24508.95,
  avgDailyTransactionVolumeMillion: 790.6113,
  transactionValueCrore: 2982355.93,
  avgDailyTransactionValueCrore: 96205.03,
  banksLiveOnUpi: 705,
  source: "NPCI",
};

export const mockUpiGrowth: UpiGrowthMetrics = {
  currentMonth: "August 2026",
  previousMonth: "July 2026",
  previousYearSameMonth: "August 2025",
  momVolumeGrowthPct: 3.59,
  momValueGrowthPct: -0.18,
  yoyVolumeGrowthPct: 22.49,
  yoyValueGrowthPct: 19.99,
  volumeTrend: "UP",
  valueTrend: "STABLE",
  avgDailyVolumeTrend: "UP",
  source: "NPCI",
};

export const mockUpiMarketSummary: UpiMarketSummary = {
  latest: mockUpiLatest,
  growth: mockUpiGrowth,
  totalMonthsAvailable: 58,
  earliestMonth: "June 2021",
  latestMonth: "September 2026",
  allTimePeakVolumeMillion: 24508.95,
  allTimePeakValueCrore: 2990424.18,
  recentTrends: mockUpiMonthlyTrends,
  source: "NPCI",
};

